services:
  redis:
    image: "redis:latest"
  rabbitmq:
    image: "rabbitmq:latest"

  wallet:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq

  celery:
    build: .
    command: celery -A core.celery_app worker -l info --concurrency=8
    depends_on:
      - wallet
  flower:
    build: .
    command: celery -A core.celery_app flower
    ports:
      - "5555:5555"
    depends_on:
      - celery

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local