# Generated by Django 5.1.4 on 2024-12-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Список кошельков'},
        ),
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание кошелька'),
        ),
    ]
