# Generated by Django 5.1.4 on 2024-12-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_options_wallet_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Список кошельков'},
        ),
    ]
