# Generated by Django 5.1.4 on 2024-12-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['created_at'], 'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Список кошельков'},
        ),
    ]
